mutation UpdateArtifact(
	$id: GlobalID!
	$name: String
	$description: String
	$markdownNotes: String
	$items: NodePartialListInput
) {
	updateArtifact(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			items: $items
		}
	) {
		... on Artifact {
			id
			name
			description
			markdownNotes
			lockTime
			lockedBySelf
			lockUser {
				id
				username
			}
			items {
				edges {
					node {
						...ItemListFields
					}
				}
			}
		}
	}
}
