mutation UpdateArtifact(
	$id: ID!
	$name: String
	$description: String
	$markdownNotes: String
	$items: NodeInputListInput
	$relatedArtifacts: NodeInputListInput
	$relatedAssociations: NodeInputListInput
	$relatedCharacters: NodeInputListInput
	$relatedItems: NodeInputListInput
	$relatedPlaces: NodeInputListInput
	$relatedRaces: NodeInputListInput
) {
	updateArtifact(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			items: $items
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Artifact {
			...ArtifactLockedBySelf
			...ArtifactDetailFields
		}
	}
}
