mutation artifactCreate(
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
	$imageIds: [String]
) {
	artifactCreate(
		input: {
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
			imageIds: $imageIds
		}
	) {
		ok
		errors
		artifact {
			...ArtifactFields
		}
	}
}
