fragment ArtifactFields on ArtifactNode {
	id
	name
	description
	imageIds
	thumbnailId
	created
	updated
	markdownNotes
	lockUser {
		id
		username
	}
	lockTime
	lockedBySelf
	logs {
		edges {
			node {
				id
				url
				name
			}
		}
	}
	items {
		edges {
			node {
				id
				name
				description
				imageIds
				thumbnailId
				armor {
					acBonus
				}
				weapon {
					attackBonus
				}
				equipment {
					briefDescription
				}
			}
		}
	}
}
