mutation associationPatch(
	$id: ID!
	$name: String
	$description: String
	$imageIds: [String]
	$thumbnailId: String
	$markdownNotes: String
) {
	associationPatch(
		input: {
			id: $id
			name: $name
			description: $description
			imageIds: $imageIds
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
		}
	) {
		ok
		errors
		association {
			id
			name
			description
			imageIds
			thumbnailId
			markdownNotes
			lockUser {
				id
				username
			}
			lockTime
			lockedBySelf
		}
	}
}
