fragment AssociationFields on AssociationNode {
	id
	name
	description
	imageIds
	thumbnailId
	markdownNotes
	lockUser {
		id
		username
	}
	lockTime
	lockedBySelf
	npcs {
		edges {
			node {
				id
				name
				description
			}
		}
	}
}
