mutation associationPatch(
	$id: ID!
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
	$npcs: [ID]
) {
	associationPatch(
		input: {
			id: $id
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
			npcs: $npcs
		}
	) {
		ok
		errors
		association {
			...AssociationFields
		}
	}
}
