mutation associationCreate(
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
	$imageIds: [String]
	$npcs: [ID]
) {
	associationCreate(
		input: {
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			npcs: $npcs
		}
	) {
		ok
		errors
		association {
			...AssociationFields
		}
	}
}
