query associations {
	associations {
		edges {
			node {
				id
				name
				description
				imageId
				thumbnailId
				markdownNotes
				lockUser {
					id
					username
				}
				lockTime
				lockedBySelf
			}
		}
	}
}
