mutation associationLock($id: ID!) {
	associationLock(input: { id: $id }) {
		ok
		errors
		association {
			id
			name
			description
			imageIds
			thumbnailId
			markdownNotes
			lockUser {
				id
				username
			}
			lockTime
			lockedBySelf
		}
	}
}
