mutation itemPatch(
	$id: ID!
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
	$armor: ArmorInput
	$equipment: EquipmentInput
	$weapon: WeaponInput
) {
	itemPatch(
		input: {
			id: $id
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
			armor: $armor
			equipment: $equipment
			weapon: $weapon
		}
	) {
		ok
		errors
		item {
			...ItemFields
		}
	}
}
