mutation itemCreate(
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
	$imageIds: [String]
	$armor: ArmorInput
	$equipment: EquipmentInput
	$weapon: WeaponInput
) {
	itemCreate(
		input: {
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			armor: $armor
			equipment: $equipment
			weapon: $weapon
		}
	) {
		ok
		errors
		item {
			...ItemFields
		}
	}
}
