fragment ItemFields on ItemNode {
	id
	name
	description
	imageIds
	thumbnailId
	markdownNotes
	lockUser {
		id
		username
	}
	lockTime
	lockedBySelf
	logs {
		edges {
			node {
				id
				url
				name
			}
		}
	}
	armor {
		acBonus
	}
	weapon {
		attackBonus
	}
	equipment {
		briefDescription
	}
}
