fragment ItemFields on ItemNode {
	id
	name
	description
	imageIds
	thumbnailId
	markdownNotes
	lockUser {
		id
		username
	}
	lockTime
	lockedBySelf
	armor {
		acBonus
	}
	weapon {
		attackBonus
	}
	equipment {
		briefDescription
	}
}
