query npcById($id: ID!) {
	npc(id: $id) {
		id
		name
		description
		imageIds
		thumbnailId
		markdownNotes
		lockUser {
			id
			username
		}
		lockTime
		size
		race {
			id
			name
			description
			imageIds
			thumbnailId
			ageOfAdulthood
			lifeExpectancy
			alignment
			size
			speed
		}
		featuresAndTraits {
			edges {
				node {
					id
					name
					description
				}
			}
		}
		proficiencies {
			edges {
				node {
					id
					name
					description
					proficiencyType
				}
			}
		}
	}
}
