mutation npcCreate(
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
	$imageIds: [String]
	$associations: [ID]
	$race: ID
) {
	npcCreate(
		input: {
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			associations: $associations
			race: $race
		}
	) {
		ok
		errors
		npc {
			...NpcFields
		}
	}
}
