fragment NpcFields on NPCNode {
	id
	name
	description
	imageIds
	thumbnailId
	markdownNotes
	lockUser {
		id
		username
	}
	lockTime
	lockedBySelf
	size
	logs {
		edges {
			node {
				id
				url
				name
			}
		}
	}
	race {
		id
		name
		description
		imageIds
		thumbnailId
		ageOfAdulthood
		lifeExpectancy
		alignment
		size
		speed
	}
	associations {
		edges {
			node {
				id
				name
				description
			}
		}
	}
	featuresAndTraits {
		edges {
			node {
				id
				name
				description
			}
		}
	}
	proficiencies {
		edges {
			node {
				id
				name
				description
				proficiencyType
			}
		}
	}
}
