mutation npcPatch(
	$id: ID!
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
	$associations: [ID]
	$race: ID
) {
	npcPatch(
		input: {
			id: $id
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
			associations: $associations
			race: $race
		}
	) {
		ok
		errors
		npc {
			...NpcFields
		}
	}
}
