mutation placeCreate(
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
	$imageIds: [String]
	$placeType: String
	$parent: ID
	$children: [ID]
) {
	placeCreate(
		input: {
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			placeType: $placeType
			parent: $parent
			children: $children
		}
	) {
		ok
		errors
		place {
			...PlaceFields
		}
	}
}
