fragment PlaceFields on Place {
	id
	name
	description
	imageIds
	thumbnailId
	markdownNotes
	lockUser {
		id
		username
	}
	lockTime
	created
	updated
	placeType
	population
	parent {
		id
		name
		description
		imageIds
		thumbnailId
		created
		updated
		placeType
		population
		parent {
			id
			name
			description
			imageIds
			thumbnailId
			created
			updated
			placeType
			population
		}
	}
}
