mutation racePatch(
	$id: ID!
	$name: String
	$description: String
	$thumbnailId: String
	$markdownNotes: String
) {
	racePatch(
		input: {
			id: $id
			name: $name
			description: $description
			thumbnailId: $thumbnailId
			markdownNotes: $markdownNotes
		}
	) {
		ok
		errors
		race {
			...RaceFields
		}
	}
}
