mutation CreatePlace(
	$name: String!
	$description: String
	$markdownNotes: String
	$imageIds: [String!]
	$logs: [ID!]
	$parent: NodeInput
	$children: NodeInputListInput
	$placeType: PlaceType
	$relatedArtifacts: NodeInputListInput
	$relatedAssociations: NodeInputListInput
	$relatedCharacters: NodeInputListInput
	$relatedItems: NodeInputListInput
	$relatedPlaces: NodeInputListInput
	$relatedRaces: NodeInputListInput
) {
	createPlace(
		input: {
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			logs: $logs
			parent: $parent
			children: $children
			placeType: $placeType
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Place {
			id
			name
		}
	}
}
