mutation EntityAddImage($id: ID!, $imageId: String!) {
	entityAddImage(input: { id: $id, imageId: $imageId }) {
		... on Artifact {
			id
			imageIds
		}
		... on Association {
			id
			imageIds
		}
		... on Character {
			id
			imageIds
		}
		... on Item {
			id
			imageIds
		}
		... on Place {
			id
			imageIds
		}
		... on Race {
			id
			imageIds
		}
	}
}
