/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */
import prisma from './prisma';
import { hello as queryHelloResolver } from './server';
import { GraphQLSchema, GraphQLObjectType, GraphQLString } from 'graphql';
export function getSchema(): GraphQLSchema {
	const QueryType: GraphQLObjectType = new GraphQLObjectType({
		name: 'Query',
		fields() {
			return {
				hello: {
					name: 'hello',
					type: GraphQLString,
					resolve(source) {
						return prisma.user.findFirst().then((user) => user?.id ?? 'No user found');
					}
				}
			};
		}
	});
	return new GraphQLSchema({
		query: QueryType,
		types: [QueryType]
	});
}
