mutation UpdateAssociation(
	$id: ID!
	$name: String
	$description: String
	$markdownNotes: String
	$characters: ManyToManyInput
	$relatedArtifacts: ManyToManyInput
	$relatedAssociations: ManyToManyInput
	$relatedCharacters: ManyToManyInput
	$relatedItems: ManyToManyInput
	$relatedPlaces: ManyToManyInput
	$relatedRaces: ManyToManyInput
) {
	updateAssociation(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			characters: $characters
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Association {
			...AssociationLockedBySelf
			...AssociationDetailFields
		}
	}
}
