mutation UpdateItem(
	$id: GlobalID!
	$name: String
	$description: String
	$markdownNotes: String
	$armor: ArmorTraitsInput
	$weapon: WeaponTraitsInput
	$equipment: EquipmentTraitsInput
	$relatedArtifacts: NodePartialListInput
	$relatedAssociations: NodePartialListInput
	$relatedCharacters: NodePartialListInput
	$relatedItems: NodePartialListInput
	$relatedPlaces: NodePartialListInput
	$relatedRaces: NodePartialListInput
) {
	updateItem(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			armor: $armor
			weapon: $weapon
			equipment: $equipment
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Item {
			...ItemLockedBySelf
			...ItemDetailFields
		}
	}
}
