import { createYoga } from 'graphql-yoga';
import { getSchema } from '$lib/api/schema.js'; // Will be generated by Grats
import type { RequestHandler } from './$types';

const yogaServer = createYoga({
	fetchAPI: { Response },
	schema: getSchema(),
	graphqlEndpoint: '/endpoints/api'
}) satisfies RequestHandler;

export { yogaServer as GET, yogaServer as POST, yogaServer as OPTIONS };
