mutation UpdateRace($id: GlobalID!, $name: String, $description: String, $markdownNotes: String) {
	updateRace(
		input: { id: $id, name: $name, description: $description, markdownNotes: $markdownNotes }
	) {
		... on Race {
			id
			name
			description
			markdownNotes
			lockTime
			lockedBySelf
			lockUser {
				id
				username
			}
		}
	}
}
