mutation UpdateRace(
	$id: ID!
	$name: String
	$description: String
	$markdownNotes: String
	$relatedArtifacts: NodeInputListInput
	$relatedAssociations: NodeInputListInput
	$relatedCharacters: NodeInputListInput
	$relatedItems: NodeInputListInput
	$relatedPlaces: NodeInputListInput
	$relatedRaces: NodeInputListInput
) {
	updateRace(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Race {
			...RaceLockedBySelf
			...RaceDetailFields
		}
	}
}
