mutation AddEntityLog($entityId: GlobalID!, $logId: GlobalID, $logUrl: String) {
	addEntityLog(input: { entityId: $entityId, logId: $logId, logUrl: $logUrl }) {
		... on Artifact {
			id
			logs {
				edges {
					node {
						googleId
						id
						title
						url
					}
				}
			}
		}
		... on Association {
			id
			logs {
				edges {
					node {
						googleId
						id
						title
						url
					}
				}
			}
		}
		... on Character {
			id
			logs {
				edges {
					node {
						googleId
						id
						title
						url
					}
				}
			}
		}
		... on Item {
			id
			logs {
				edges {
					node {
						googleId
						id
						title
						url
					}
				}
			}
		}
		... on Place {
			id
			logs {
				edges {
					node {
						googleId
						id
						title
						url
					}
				}
			}
		}
		... on Race {
			id
			logs {
				edges {
					node {
						googleId
						id
						title
						url
					}
				}
			}
		}
	}
}
