mutation UpdateCharacter(
	$id: GlobalID!
	$name: String
	$description: String
	$markdownNotes: String
	$race: NodeInput
	$associations: NodePartialListInput
	$relatedArtifacts: NodePartialListInput
	$relatedAssociations: NodePartialListInput
	$relatedCharacters: NodePartialListInput
	$relatedItems: NodePartialListInput
	$relatedPlaces: NodePartialListInput
	$relatedRaces: NodePartialListInput
) {
	updateCharacter(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			race: $race
			associations: $associations
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Character {
			...CharacterLockedBySelf
			...CharacterDetailFields
		}
	}
}
