mutation UpdateCharacter(
	$id: ID!
	$name: String
	$description: String
	$markdownNotes: String
	$race: OneToManyInput
	$associations: ManyToManyInput
	$relatedArtifacts: ManyToManyInput
	$relatedAssociations: ManyToManyInput
	$relatedCharacters: ManyToManyInput
	$relatedItems: ManyToManyInput
	$relatedPlaces: ManyToManyInput
	$relatedRaces: ManyToManyInput
) {
	updateCharacter(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			race: $race
			associations: $associations
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Character {
			...CharacterLockedBySelf
			...CharacterDetailFields
		}
	}
}
