query ChatSessions($first: Int = 20) {
	chatSessions(first: $first) {
		edges {
			node {
				id
				title
				createdAt
				updatedAt
				messages {
					id
					message
					response
					createdAt
				}
			}
		}
	}
}
