mutation CreateCharacter(
	$name: String!
	$description: String
	$markdownNotes: String
	$imageIds: [String!]
	$logs: [ID!]
	$race: OneToManyInput
	$associations: ManyToManyInput
	$relatedArtifacts: ManyToManyInput
	$relatedAssociations: ManyToManyInput
	$relatedCharacters: ManyToManyInput
	$relatedItems: ManyToManyInput
	$relatedPlaces: ManyToManyInput
	$relatedRaces: ManyToManyInput
) {
	createCharacter(
		input: {
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			logs: $logs
			race: $race
			associations: $associations
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Character {
			id
			name
		}
	}
}
