mutation CreateCharacter($name: String!, $description: String, $markdownNotes: String) {
	createCharacter(
		input: { name: $name, description: $description, markdownNotes: $markdownNotes }
	) {
		... on Character {
			id
		}
	}
}
