mutation CreateRace(
	$name: String!
	$description: String
	$markdownNotes: String
	$imageIds: [String!]
	$logs: [GlobalID!]
	$relatedArtifacts: NodePartialListInput
	$relatedAssociations: NodePartialListInput
	$relatedCharacters: NodePartialListInput
	$relatedItems: NodePartialListInput
	$relatedPlaces: NodePartialListInput
	$relatedRaces: NodePartialListInput
) {
	createRace(
		input: {
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			logs: $logs
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Race {
			id
			name
		}
	}
}
