mutation CreateAssociation(
	$name: String!
	$description: String
	$markdownNotes: String
	$imageIds: [String!]
	$logs: [ID!]
	$characters: NodeInputListInput
	$relatedArtifacts: NodeInputListInput
	$relatedAssociations: NodeInputListInput
	$relatedCharacters: NodeInputListInput
	$relatedItems: NodeInputListInput
	$relatedPlaces: NodeInputListInput
	$relatedRaces: NodeInputListInput
) {
	createAssociation(
		input: {
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			logs: $logs
			characters: $characters
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Association {
			id
			name
			...AssociationLockedBySelf
			...AssociationDetailFields
		}
	}
}
