mutation CreateItem(
	$name: String!
	$description: String
	$markdownNotes: String
	$imageIds: [String!]
	$logs: [ID!]
	$armor: ArmorTraitsInput
	$weapon: WeaponTraitsInput
	$equipment: EquipmentTraitsInput
	$relatedArtifacts: NodeInputListInput
	$relatedAssociations: NodeInputListInput
	$relatedCharacters: NodeInputListInput
	$relatedItems: NodeInputListInput
	$relatedPlaces: NodeInputListInput
	$relatedRaces: NodeInputListInput
) {
	createItem(
		input: {
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			imageIds: $imageIds
			logs: $logs
			armor: $armor
			weapon: $weapon
			equipment: $equipment
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Item {
			id
			name
		}
	}
}
