mutation UpdatePlace(
	$id: GlobalID!
	$name: String
	$description: String
	$markdownNotes: String
	$parent: NodeInput
	$children: NodeListInput
	$placeType: PlaceType
	$relatedArtifacts: NodePartialListInput
	$relatedAssociations: NodePartialListInput
	$relatedCharacters: NodePartialListInput
	$relatedItems: NodePartialListInput
	$relatedPlaces: NodePartialListInput
	$relatedRaces: NodePartialListInput
) {
	updatePlace(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			parent: $parent
			children: $children
			placeType: $placeType
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Place {
			...PlaceLockedBySelf
			...PlaceDetailFields
		}
	}
}
