mutation UpdatePlace(
	$id: ID!
	$name: String
	$description: String
	$markdownNotes: String
	$parent: NodeInput
	$children: NodeInputListInput
	$placeType: PlaceType
	$relatedArtifacts: NodeInputListInput
	$relatedAssociations: NodeInputListInput
	$relatedCharacters: NodeInputListInput
	$relatedItems: NodeInputListInput
	$relatedPlaces: NodeInputListInput
	$relatedRaces: NodeInputListInput
) {
	updatePlace(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			parent: $parent
			children: $children
			placeType: $placeType
			relatedArtifacts: $relatedArtifacts
			relatedAssociations: $relatedAssociations
			relatedCharacters: $relatedCharacters
			relatedItems: $relatedItems
			relatedPlaces: $relatedPlaces
			relatedRaces: $relatedRaces
		}
	) {
		... on Place {
			...PlaceLockedBySelf
			...PlaceDetailFields
		}
	}
}
